### ISSUE TITLE
logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [darshanparajuli/jobpool#1]
Hello Darshan, do you want a logo for this project?

**Comment by Arslanshn** [comment]
https://drive.google.com/folderview?id=1fybOxpmofis300TxIFmiF0LboyZXweuz

**Comment by Arslanshn** [comment]
Hi Darshanparajuli 😀

**Comment by darshanparajuli** [comment]
Hey @Arslanshn, sorry for the late reply. 
This project is no longer actively maintained, so a logo is not necessary. Thanks though!
